fix: fixed config UI input not refreshing

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -23,6 +23,10 @@ jobs:
         run: |
           RAW_BRANCH=$(git branch -r --contains ${{ github.ref_name }} | grep -v HEAD | grep origin | head -n 1)
           BRANCH_NAME=$(echo $RAW_BRANCH | sed -e 's/^[[:space:]]*origin\///')
+          if [ -z "$BRANCH_NAME" ]; then
+            echo "Error: No remote branch found containing tag ${{ github.ref_name }}."
+            exit 1
+          fi
           echo "Found branch: $BRANCH_NAME"
           echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
 
@@ -48,7 +52,16 @@ jobs:
           name: Artifacts
           path: build/libs/
 
-      - name: Generate Changelog with git-cliff
+      - name: Incremental Changelog for Release Body
+        uses: orhun/git-cliff-action@v4
+        id: git-cliff-body
+        with:
+          config: config/cliff.toml
+          args: --latest --strip header
+        env:
+          GITHUB_REPO: ${{ github.repository }}
+
+      - name: Full Changelog for file
         uses: orhun/git-cliff-action@v4
         id: git-cliff
         with:
@@ -61,7 +74,7 @@ jobs:
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
         with:
-          body: ${{ steps.git-cliff.outputs.content }}
+          body: ${{ steps.git-cliff-body.outputs.content }}
           files: build/libs/*.jar
           draft: true
 
